import {
    Activity,
    ArrowLeft,
    ArrowRight,
    Bell,
    Boxes,
    ChevronLeft,
    ChevronRight,
    CircleCheckBig,
    CircleX,
    Code,
    Copy,
    Database,
    ExternalLink,
    Eye,
    EyeOff,
    FileUp,
    Grid2x2,
    HelpCircle,
    Home,
    KeyRound,
    LayoutDashboard,
    LogOut,
    Monitor,
    Network,
    Pencil,
    Plus,
    RefreshCw,
    Search,
    Settings,
    Smile,
    Store,
    Trash2,
    TriangleAlert,
    Upload,
    User,
    UserCircle,
    X,
    XSquare,
    Zap,
} from 'lucide-vue-next';

export const saxIcon = {
    control:       Monitor,
    update:        Zap,
    appearance:    Smile,
    profile:       UserCircle,
    routes:        Network,
    home:          Home,
    arrowLeft:     ArrowLeft,
    arrowRight:    ArrowRight,
    apps:          Boxes,
    manager:       LayoutDashboard,
    pincore:       Code,
    back:          ChevronRight,
    add:           Plus,
    guide:         HelpCircle,
    tips:          Activity,
    edit:          Pencil,
    setting:       Settings,
    close:         CircleX,
    remove:        Trash2,
    upload:        FileUp,
    market:        Store,
    search:        Search,
    widgets:       Grid2x2,
    refresh:       RefreshCw,
    lock:          KeyRound,
    copy:          Copy,
    externalLink:  ExternalLink,
    logout:        LogOut,
    user:          User,
    notifySuccess: CircleCheckBig,
    notifyError:   CircleX,
    notifyWarn:    TriangleAlert,
    notifyInfo:    Bell,
    notifyClose:   XSquare,
    data:          Database,
    eye:           Eye,
    eyeOff:        EyeOff,
};

export const lucideSidebar = {
    close:        'x',
    widgets:      'layout-grid',
    apps:         'boxes',
    upload:       'upload',
    routes:       'route',
    setting:      'settings',
    profile:      'user',
    pincore:      'code',
    market:       'store',
    chevronLeft:  'chevron-left',
    chevronRight: 'chevron-right',
    menu:         'menu',
};
