import { getBoot } from '@/boot.js';
import { useOptionsStore } from '@/stores/modules/options.js';

const MESSAGES = {
    fa: {
        unknown_app: 'برنامه نامشخص',
        system_app_manager: 'منجر — مدیریت پینوکس',
        app_single_route_only: 'این برنامه فقط یک آدرس می‌پذیرد (در app.php با type: single)',
        route_action_edit: 'ویرایش',
        route_action_delete: 'حذف',
        route_action_no_delete: 'غیرقابل حذف',
        route_actions_locked: 'آدرس ثابت — قابل ویرایش نیست',
        route_actions_unavailable: 'عملیاتی وجود ندارد',
        route_url_copy: 'کپی آدرس',
        route_url_copied: 'کپی شد',
        route_url_open: 'باز کردن در تب جدید',
        route_delete_title: 'حذف آدرس',
        route_delete_lead: 'آیا از حذف این مسیریابی مطمئن هستید؟',
        route_delete_hint: 'با حذف، این آدرس دیگر به برنامه‌ای متصل نخواهد بود.',
        route_delete_cancel: 'انصراف',
        route_delete_confirm: 'بله، حذف شود',
        route_delete_progress: 'در حال حذف…',
        route_save_progress_create: 'در حال ایجاد آدرس…',
        route_save_progress_edit: 'در حال ذخیره آدرس…',
        route_save_progress_home: 'در حال ذخیره…',
        route_save_success_create: 'آدرس با موفقیت ایجاد شد',
        route_save_success_edit: 'آدرس ذخیره شد',
        route_save_success_home: 'برنامهٔ صفحه اصلی ذخیره شد',
        route_path_duplicate: 'این آدرس قبلاً ثبت شده و به برنامه «{app}» متصل است.',
        are_you_sure_delete_app: 'حذف این برنامه؟',
        are_you_sure_reset_app: 'بازنشانی این برنامه؟',
        cannot_delete_system_app: 'این برنامه بخشی از سیستم است و قابل حذف نیست.',
        cannot_reset_system_app: 'این برنامه بخشی از سیستم است و قابل بازنشانی نیست.',
        app_uninstall_lead: 'این برنامه از سایت شما پاک می‌شود.',
        app_uninstall_hint: 'فایل‌های برنامه و آدرس‌های متصل به آن حذف می‌شوند. امکان بازگردانی وجود ندارد.',
        app_uninstall_purge_title: 'فایل‌ها و داده‌ها هم پاک شود',
        app_uninstall_purge_hint: 'جداول دیتابیس، رکوردهای فایل و پوشهٔ storage این برنامه هم حذف می‌شوند.',
        app_uninstall_routes_warning: 'این برنامه به {count} آدرس متصل است. با حذف برنامه، این آدرس‌ها هم حذف می‌شوند:',
        app_uninstall_routes_single: 'این برنامه به آدرس {path} متصل است. با حذف برنامه، این آدرس هم حذف می‌شود.',
        app_uninstall_confirm: 'بله، حذف شود',
        app_uninstall_progress: 'در حال حذف برنامه…',
        cancel: 'انصراف',
        delete_successfully: 'برنامه با موفقیت حذف شد',
        reset_successfully: 'برنامه با موفقیت بازنشانی شد',
        app_details_about: 'درباره برنامه',
        app_details_no_description: 'توضیحی برای این برنامه ثبت نشده است.',
        app_details_addresses: 'آدرس‌های فعال',
        app_details_more_addresses: 'آدرس دیگر',
        app_details_addresses_empty: 'هنوز آدرسی به این برنامه وصل نیست',
        app_details_addresses_empty_hint: 'از بخش مسیریابی یک آدرس عمومی برای بازدیدکننده‌ها تعریف کنید.',
        app_details_manage_routes: 'مدیریت آدرس‌ها',
        app_details_home_badge: 'صفحه اصلی',
        app_details_danger_zone: 'منطقه خطر',
        app_data_storage: 'حجم ذخیره‌سازی',
        app_data_storage_hint: '{files} فایل آپلودشده · حجم کد برنامه {package}',
        app_data_storage_hint_files: '{files} فایل آپلودشده',
        app_data_storage_hint_package: 'حجم کد برنامه {package}',
        app_data_storage_empty: 'هنوز فایلی در storage این برنامه نیست',
        app_data_stat_files: 'فایل‌ها',
        app_data_stat_users: 'کاربران',
        app_data_stat_routes: 'آدرس‌ها',
        app_data_stat_package: 'حجم برنامه',
        app_data_stat_migrations: 'مایگریشن',
        app_data_stat_patches: 'پچ‌ها',
        app_run: 'باز کردن برنامه',
        app_settings: 'تنظیمات',
        app_templates: 'قالب‌ها',
        app_badge_system: 'برنامه سیستمی',
        app_badge_hidden: 'مخفی',
        app_badge_no_dock: 'بدون میانبر',
        app_system_notice: 'این برنامه بخشی از سیستم پینوکس است و از اینجا قابل حذف یا بازنشانی نیست.',
        app_reset_title: 'بازنشانی برنامه',
        app_reset_intro: 'همهٔ داده‌های برنامه پاک می‌شود و migrations و patches از نو اجرا می‌شوند. خود برنامه نصب‌مانده می‌ماند.',
        app_reset_button: 'بازنشانی این برنامه',
        app_reset_lead: 'داده‌های این برنامه از نو ساخته می‌شوند.',
        app_reset_hint: 'جداول دیتابیس حذف و دوباره ساخته می‌شوند، سپس پچ‌ها اجرا می‌گردند. این کار قابل بازگشت نیست.',
        app_reset_purge_storage_title: 'فایل‌های آپلودشده (storage) هم پاک شود',
        app_reset_purge_storage_hint: 'عکس‌ها، اسناد و سایر فایل‌های ذخیره‌شدهٔ این برنامه حذف می‌شوند.',
        app_reset_confirm: 'بله، بازنشانی شود',
        app_reset_progress: 'در حال بازنشانی برنامه…',
        app_uninstall_title: 'حذف برنامه',
        app_uninstall_intro: 'با حذف این برنامه، فایل‌های آن از سایت پاک می‌شود. در صورت تمایل می‌توانید داده‌ها و فایل‌های storage را هم حذف کنید.',
        app_uninstall_button: 'حذف این برنامه',
        app_stat_version: 'نسخه',
        app_stat_version_code: 'شماره نسخه',
        app_stat_developer: 'سازنده',
        app_stat_package: 'شناسه برنامه',
        app_stat_routing: 'نوع آدرس',
        app_stat_address_count: 'تعداد آدرس',
        app_routing_single: 'یک آدرس',
        app_routing_multiple: 'چند آدرس',
        template_activate_button: 'فعال‌سازی',
        template_delete_button: 'حذف قالب',
        template_active_badge: 'قالب فعال',
        template_active_no_delete: 'قالب فعال قابل حذف نیست.',
        template_delete_confirm: 'آیا از حذف این قالب مطمئن هستید؟',
    },
    en: {
        unknown_app: 'Unknown app',
        system_app_manager: 'Manager — Pinoox Control Panel',
        app_single_route_only: 'This app accepts only one URL (router.type: single in app.php)',
        route_action_edit: 'Edit',
        route_action_delete: 'Delete',
        route_action_no_delete: 'Cannot delete',
        route_actions_locked: 'Fixed route — not editable',
        route_actions_unavailable: 'No actions available',
        route_url_copy: 'Copy address',
        route_url_copied: 'Copied',
        route_url_open: 'Open in new tab',
        route_delete_title: 'Delete route',
        route_delete_lead: 'Are you sure you want to delete this route?',
        route_delete_hint: 'After deletion, this address will no longer be linked to an app.',
        route_delete_cancel: 'Cancel',
        route_delete_confirm: 'Yes, delete',
        route_delete_progress: 'Deleting…',
        route_save_progress_create: 'Creating address…',
        route_save_progress_edit: 'Saving address…',
        route_save_progress_home: 'Saving…',
        route_save_success_create: 'Address created successfully',
        route_save_success_edit: 'Address saved',
        route_save_success_home: 'Homepage app saved',
        route_path_duplicate: 'This address already exists and is linked to «{app}».',
        are_you_sure_delete_app: 'Remove this app?',
        are_you_sure_reset_app: 'Reset this app?',
        cannot_delete_system_app: 'This app is part of the system and cannot be removed.',
        cannot_reset_system_app: 'This app is part of the system and cannot be reset.',
        app_uninstall_lead: 'This app will be removed from your site.',
        app_uninstall_hint: 'App files and linked routes will be removed. This cannot be undone.',
        app_uninstall_purge_title: 'Also delete files and data',
        app_uninstall_purge_hint: 'Also remove database tables, file records, and this app’s storage folder.',
        app_uninstall_routes_warning: 'This app is linked to {count} addresses. Removing the app will delete these routes too:',
        app_uninstall_routes_single: 'This app is linked to {path}. Removing the app will delete this route too.',
        app_uninstall_confirm: 'Yes, remove it',
        app_uninstall_progress: 'Removing app…',
        cancel: 'Cancel',
        delete_successfully: 'App removed successfully',
        reset_successfully: 'App reset successfully',
        app_details_about: 'About this app',
        app_details_no_description: 'No description is set for this app.',
        app_details_addresses: 'Active addresses',
        app_details_more_addresses: 'more addresses',
        app_details_addresses_empty: 'This app has no public address yet',
        app_details_addresses_empty_hint: 'Add a public URL for visitors from the routing page.',
        app_details_manage_routes: 'Manage addresses',
        app_details_home_badge: 'Homepage',
        app_details_danger_zone: 'Danger zone',
        app_data_storage: 'Storage size',
        app_data_storage_hint: '{files} uploaded files · app code {package}',
        app_data_storage_hint_files: '{files} uploaded files',
        app_data_storage_hint_package: 'App code {package}',
        app_data_storage_empty: 'This app has no storage files yet',
        app_data_stat_files: 'Files',
        app_data_stat_users: 'Users',
        app_data_stat_routes: 'Addresses',
        app_data_stat_package: 'App size',
        app_data_stat_migrations: 'Migrations',
        app_data_stat_patches: 'Patches',
        app_run: 'Open app',
        app_settings: 'Settings',
        app_templates: 'Themes',
        app_badge_system: 'System app',
        app_badge_hidden: 'Hidden',
        app_badge_no_dock: 'No shortcut',
        app_system_notice: 'This app is part of Pinoox and cannot be removed or reset from here.',
        app_reset_title: 'Reset app',
        app_reset_intro: 'All app data is wiped and migrations and patches run again. The app itself stays installed.',
        app_reset_button: 'Reset this app',
        app_reset_lead: 'This app’s data will be rebuilt from scratch.',
        app_reset_hint: 'Database tables are dropped and recreated, then patches run. This cannot be undone.',
        app_reset_purge_storage_title: 'Also delete uploaded files (storage)',
        app_reset_purge_storage_hint: 'Images, documents, and other stored files for this app will be deleted.',
        app_reset_confirm: 'Yes, reset it',
        app_reset_progress: 'Resetting app…',
        app_uninstall_title: 'Remove app',
        app_uninstall_intro: 'Removing this app deletes its files from your site. You can optionally delete its data and storage files too.',
        app_uninstall_button: 'Remove this app',
        app_stat_version: 'Version',
        app_stat_version_code: 'Version number',
        app_stat_developer: 'Developer',
        app_stat_package: 'App ID',
        app_stat_routing: 'Address type',
        app_stat_address_count: 'Address count',
        app_routing_single: 'Single address',
        app_routing_multiple: 'Multiple addresses',
        template_activate_button: 'Activate',
        template_delete_button: 'Delete template',
        template_active_badge: 'Active theme',
        template_active_no_delete: 'The active theme cannot be deleted.',
        template_delete_confirm: 'Are you sure you want to delete this template?',
    },
};

export function resolveLocale(lang) {
    const code = String(lang ?? readActiveLang() ?? 'fa').toLowerCase();

    if (code.startsWith('fa')) {
        return 'fa';
    }

    return 'en';
}

function readActiveLang() {
    try {
        const store = useOptionsStore();

        if (store.lang) {
            return store.lang;
        }
    } catch {
        // Pinia may not be ready during early boot.
    }

    return getBoot().locale ?? document.documentElement.lang ?? 'fa';
}

export function translate(key, lang) {
    const locale = resolveLocale(lang);
    return MESSAGES[locale]?.[key] ?? MESSAGES.en[key] ?? key;
}
