import { getBoot } from '@/boot.js';
import { useOptionsStore } from '@/stores/modules/options.js';

const MESSAGES = {
    fa: {
        unknown_app: 'برنامه نامشخص',
        system_app_manager: 'منجر — مدیریت پینوکس',
        app_single_route_only: 'این برنامه فقط یک آدرس می‌تواند داشته باشد.',
        route_action_edit: 'ویرایش',
        route_action_delete: 'حذف',
        route_action_no_delete: 'غیرقابل حذف',
        route_actions_locked: 'این آدرس ثابت است و قابل تغییر نیست',
        route_actions_unavailable: 'عملیاتی وجود ندارد',
        route_url_copy: 'کپی آدرس',
        route_url_copied: 'کپی شد',
        route_url_open: 'باز کردن در تب جدید',
        route_delete_title: 'حذف آدرس',
        route_delete_lead: 'می‌خواهید این آدرس حذف شود؟',
        route_delete_hint: 'بعد از حذف، این لینک دیگر برنامه را باز نمی‌کند.',
        route_delete_cancel: 'انصراف',
        route_delete_confirm: 'بله، حذف شود',
        route_delete_progress: 'در حال حذف…',
        route_save_progress_create: 'در حال ساخت آدرس…',
        route_save_progress_edit: 'در حال ذخیره…',
        route_save_progress_home: 'در حال ذخیره…',
        route_save_success_create: 'آدرس ذخیره شد',
        route_save_success_edit: 'آدرس به‌روز شد',
        route_save_success_home: 'صفحهٔ اصلی به‌روز شد',
        route_path_duplicate: 'این آدرس قبلاً برای برنامه «{app}» ثبت شده است.',
        are_you_sure_delete_app: 'این برنامه حذف شود؟',
        are_you_sure_reset_app: 'این برنامه از نو شروع شود؟',
        cannot_delete_system_app: 'این برنامه بخشی از سیستم است و حذف نمی‌شود.',
        cannot_reset_system_app: 'این برنامه بخشی از سیستم است و از نو شروع نمی‌شود.',
        app_uninstall_lead: 'این برنامه از سایت شما حذف می‌شود.',
        app_uninstall_hint: 'خود برنامه و لینک‌هایش پاک می‌شوند. این کار برگشت ندارد.',
        app_uninstall_purge_title: 'اطلاعات و فایل‌هایش هم پاک شود',
        app_uninstall_purge_hint: 'عکس‌ها، فایل‌ها و اطلاعات ذخیره‌شدهٔ این برنامه هم حذف می‌شوند.',
        app_uninstall_routes_warning: 'این برنامه به {count} آدرس وصل است. با حذف برنامه این آدرس‌ها هم پاک می‌شوند:',
        app_uninstall_routes_single: 'این برنامه به آدرس {path} وصل است. با حذف برنامه این آدرس هم پاک می‌شود.',
        app_uninstall_confirm: 'بله، حذف شود',
        app_uninstall_progress: 'در حال حذف…',
        cancel: 'انصراف',
        delete_successfully: 'برنامه حذف شد',
        reset_successfully: 'برنامه از نو شروع شد',
        app_nav_details: 'معرفی',
        app_nav_config: 'تنظیمات',
        app_nav_users: 'کاربران',
        app_nav_templates: 'ظاهر',
        app_nav_data: 'فضا و مدیریت',
        app_nav_aria: 'بخش‌های مدیریت برنامه',
        app_details_about: 'معرفی',
        app_details_no_description: 'هنوز توضیحی برای این برنامه نوشته نشده است.',
        app_details_addresses: 'آدرس‌های سایت',
        app_details_more_addresses: 'آدرس دیگر',
        app_details_addresses_empty: 'هنوز آدرسی برای این برنامه ندارید',
        app_details_addresses_empty_hint: 'از بخش آدرس‌ها یک لینک برای بازدیدکننده‌ها بسازید.',
        app_details_addresses_empty_add_hint: 'یک آدرس بسازید تا مردم بتوانند این برنامه را در سایت شما باز کنند.',
        app_details_add_route: 'ساخت آدرس',
        app_details_manage_routes: 'همهٔ آدرس‌ها',
        app_details_home_badge: 'صفحهٔ اصلی سایت',
        app_details_danger_zone: 'اقدامات حساس',
        app_data_storage: 'فضای استفاده‌شده',
        app_data_storage_hint: '{files} فایل آپلودشده · خود برنامه {package}',
        app_data_storage_hint_files: '{files} فایل آپلودشده',
        app_data_storage_hint_package: 'حجم خود برنامه: {package}',
        app_data_storage_empty: 'هنوز فایلی برای این برنامه آپلود نشده است',
        app_data_stat_files: 'فایل‌های آپلودشده',
        app_data_stat_users: 'کاربران',
        app_data_stat_routes: 'آدرس‌ها',
        app_data_stat_package: 'حجم خود برنامه',
        app_data_stat_migrations: 'به‌روزرسانی‌های دیتابیس',
        app_data_stat_patches: 'اصلاحات اضافه',
        app_run: 'باز کردن برنامه',
        app_secret_view: 'مشاهده برنامه',
        app_secret_view_hint: 'باز کردن از اینجا',
        app_back: 'بازگشت',
        app_not_found_title: 'برنامه پیدا نشد',
        app_not_found_desc: 'این برنامه نصب نشده یا قبلاً حذف شده است.',
        app_settings: 'تنظیمات',
        app_templates: 'ظاهر',
        app_users_title: 'کاربران',
        app_users_intro: 'کسانی که می‌توانند وارد این برنامه شوند.',
        app_users_platform_notice: 'سیستم کاربری این برنامه با پنل مدیریت یکی است. اگر کسی اینجا باشد، با همین اطلاعات می‌تواند وارد منجر هم بشود.',
        app_users_platform_notice_form: 'با همین اطلاعات می‌تواند وارد منجر هم بشود.',
        app_users_add: 'افزودن کاربر',
        app_users_search_placeholder: 'نام، ایمیل یا شناسه',
        app_users_filter_status: 'وضعیت',
        app_users_filter_group: 'گروه کاربری',
        app_users_filter_role: 'نقش',
        app_users_filter_level: 'نقش',
        app_users_filter_all: 'همه',
        app_users_col_id: 'شناسه',
        app_users_col_name: 'نام',
        app_users_col_username: 'نام کاربری',
        app_users_col_mobile: 'موبایل',
        app_users_col_email: 'ایمیل',
        app_users_col_status: 'وضعیت',
        app_users_col_group: 'گروه کاربری',
        app_users_col_roles: 'نقش‌ها',
        app_users_col_level: 'نقش',
        app_users_col_date: 'تاریخ عضویت',
        app_users_col_actions: 'عملیات',
        app_users_col_key: 'شناسه',
        app_users_empty_value: 'ثبت نشده',
        app_users_empty: 'هنوز کاربری ثبت نشده است',
        app_users_empty_filtered: 'با این جستجو یا فیلتر کسی پیدا نشد',
        app_users_table_caption: 'فهرست کاربران این برنامه',
        app_users_count: '{count} کاربر',
        app_users_roles_title: 'نقش‌ها',
        app_users_roles_caption: 'هر نقش مشخص می‌کند کاربر چه کارهایی می‌تواند انجام دهد.',
        app_users_permissions_title: 'دسترسی‌ها',
        app_users_permissions_caption: 'کارهایی که در این برنامه تعریف شده‌اند.',
        app_users_edit: 'ویرایش',
        app_users_delete: 'حذف',
        app_users_edit_role: 'ویرایش دسترسی',
        app_users_status_active: 'فعال',
        app_users_status_inactive: 'غیرفعال',
        app_users_status_suspend: 'معلق',
        app_users_status_pending: 'در انتظار',
        app_users_form_add_title: 'افزودن کاربر',
        app_users_form_edit_title: 'ویرایش کاربر',
        app_users_form_fname: 'نام',
        app_users_form_lname: 'نام خانوادگی',
        app_users_form_username: 'نام کاربری',
        app_users_form_email: 'ایمیل',
        app_users_form_mobile: 'موبایل',
        app_users_form_password: 'رمز عبور',
        app_users_form_password_hint: 'اگر خالی بماند، رمز فعلی عوض نمی‌شود.',
        app_users_form_status: 'وضعیت',
        app_users_form_group: 'گروه کاربری',
        app_users_form_group_hint: 'می‌تواند خالی باشد',
        app_users_form_group_none: 'بدون گروه کاربری',
        app_users_form_roles: 'نقش‌ها',
        app_users_form_level: 'نقش در این برنامه',
        app_users_form_level_none: 'بدون نقش',
        app_users_level_admin: 'مدیر',
        app_users_level_superadmin: 'مدیر اصلی',
        app_users_level_manager: 'مدیر برنامه',
        app_users_level_user: 'کاربر',
        app_users_level_editor: 'ویرایشگر',
        app_users_level_guest: 'مهمان',
        app_users_form_save: 'ذخیره',
        app_users_saved: 'کاربر ذخیره شد',
        app_users_save_failed: 'ذخیره کاربر انجام نشد',
        app_users_deleted: 'کاربر حذف شد',
        app_users_delete_failed: 'حذف کاربر انجام نشد',
        app_users_delete_title: 'حذف کاربر',
        app_users_delete_lead: 'این کاربر از برنامه حذف شود؟',
        app_users_delete_hint: 'بعد از حذف، دیگر نمی‌تواند وارد این برنامه شود.',
        app_users_delete_confirm: 'بله، حذف شود',
        app_users_delete_self: 'حساب خودتان را نمی‌توانید حذف کنید',
        app_users_page: 'صفحه',
        app_users_per_page: 'تعداد در صفحه',
        app_users_prev: 'قبلی',
        app_users_next: 'بعدی',
        app_users_role_access_title: 'دسترسی‌های نقش',
        app_users_role_access_hint: 'انتخاب کنید این نقش چه کارهایی را اجازه بدهد.',
        app_users_role_access_saved: 'دسترسی‌های نقش ذخیره شد',
        app_users_no_permissions: 'هنوز دسترسی‌ای تعریف نشده',
        app_users_no_roles_assigned: 'بدون نقش',
        app_users_access_button: 'نقش‌ها و دسترسی‌ها',
        app_users_access_title: 'نقش‌ها و دسترسی‌ها',
        app_users_access_hint: 'نقش‌ها و دسترسی‌های این برنامه را اینجا ببینید.',
        app_users_access_empty: 'برای این برنامه نقش یا دسترسی‌ای تعریف نشده است.',
        app_users_groups_title: 'گروه‌ها',
        app_users_perm_other: 'سایر',
        app_templates_empty: 'قالبی پیدا نشد',
        app_config_title: 'تنظیمات',
        app_config_multi_route_title: 'چند آدرس برای این برنامه',
        app_config_multi_route_hint: 'اگر روشن باشد، می‌توانید چند لینک مختلف به همین برنامه بدهید.',
        app_badge_system: 'سیستمی',
        app_badge_hidden: 'مخفی از فهرست',
        app_badge_no_dock: 'بدون میانبر سریع',
        app_system_notice: 'این برنامه بخشی از پینوکس است؛ از اینجا حذف یا از نو شروع نمی‌شود.',
        app_reset_title: 'ریست برنامه',
        app_reset_intro: 'اطلاعات برنامه پاک می‌شود و برنامه مثل روز اول از نو آماده می‌شود. خود برنامه روی سایت می‌ماند.',
        app_reset_button: 'ریست برنامه',
        app_reset_lead: 'اطلاعات این برنامه پاک و از نو ساخته می‌شود.',
        app_reset_hint: 'اطلاعات ذخیره‌شده حذف و دوباره ساخته می‌شود. این کار برگشت ندارد.',
        app_reset_purge_storage_title: 'فایل‌های آپلودشده هم پاک شود',
        app_reset_purge_storage_hint: 'عکس‌ها، سندها و فایل‌هایی که برای این برنامه آپلود شده‌اند هم حذف می‌شوند.',
        app_reset_confirm: 'بله، از نو شروع شود',
        app_reset_progress: 'در حال شروع دوباره…',
        app_uninstall_title: 'حذف برنامه',
        app_uninstall_intro: 'برنامه از سایت حذف می‌شود. اگر بخواهید، اطلاعات و فایل‌هایش هم پاک می‌شوند.',
        app_uninstall_button: 'حذف برنامه',
        app_stat_version: 'نسخه',
        app_stat_version_code: 'کد نسخه',
        app_stat_developer: 'سازنده',
        app_stat_package: 'شناسه برنامه',
        app_stat_routing: 'نوع آدرس',
        app_stat_address_count: 'تعداد آدرس',
        app_routing_single: 'یک آدرس',
        app_routing_multiple: 'چند آدرس',
        template_activate_button: 'فعال کردن',
        template_delete_button: 'حذف ظاهر',
        template_active_badge: 'ظاهر فعال',
        template_active_no_delete: 'ظاهر فعال را نمی‌توان حذف کرد.',
        template_delete_confirm: 'می‌خواهید این ظاهر حذف شود؟',
    },
    en: {
        unknown_app: 'Unknown app',
        system_app_manager: 'Manager — Pinoox Control Panel',
        app_single_route_only: 'This app can only have one address.',
        route_action_edit: 'Edit',
        route_action_delete: 'Delete',
        route_action_no_delete: 'Cannot delete',
        route_actions_locked: 'This address is fixed and cannot be changed',
        route_actions_unavailable: 'No actions available',
        route_url_copy: 'Copy address',
        route_url_copied: 'Copied',
        route_url_open: 'Open in a new tab',
        route_delete_title: 'Delete address',
        route_delete_lead: 'Do you want to delete this address?',
        route_delete_hint: 'After deletion, this link will no longer open the app.',
        route_delete_cancel: 'Cancel',
        route_delete_confirm: 'Yes, delete it',
        route_delete_progress: 'Deleting…',
        route_save_progress_create: 'Creating address…',
        route_save_progress_edit: 'Saving…',
        route_save_progress_home: 'Saving…',
        route_save_success_create: 'Address saved',
        route_save_success_edit: 'Address updated',
        route_save_success_home: 'Homepage updated',
        route_path_duplicate: 'This address is already used by «{app}».',
        are_you_sure_delete_app: 'Remove this app?',
        are_you_sure_reset_app: 'Start this app over?',
        cannot_delete_system_app: 'This is a system app and cannot be removed.',
        cannot_reset_system_app: 'This is a system app and cannot be started over.',
        app_uninstall_lead: 'This app will be removed from your site.',
        app_uninstall_hint: 'The app and its links will be removed. This cannot be undone.',
        app_uninstall_purge_title: 'Also delete its files and data',
        app_uninstall_purge_hint: 'Uploaded images, files, and saved data for this app will be removed too.',
        app_uninstall_routes_warning: 'This app is linked to {count} addresses. Removing the app will delete these addresses too:',
        app_uninstall_routes_single: 'This app is linked to {path}. Removing the app will delete this address too.',
        app_uninstall_confirm: 'Yes, remove it',
        app_uninstall_progress: 'Removing…',
        cancel: 'Cancel',
        delete_successfully: 'App removed',
        reset_successfully: 'App started over',
        app_nav_details: 'Overview',
        app_nav_config: 'Settings',
        app_nav_users: 'Users',
        app_nav_templates: 'Look',
        app_nav_data: 'Space & manage',
        app_nav_aria: 'App sections',
        app_details_about: 'Overview',
        app_details_no_description: 'No description has been written for this app yet.',
        app_details_addresses: 'Site addresses',
        app_details_more_addresses: 'more addresses',
        app_details_addresses_empty: 'This app has no address yet',
        app_details_addresses_empty_hint: 'Create a link for visitors from the addresses page.',
        app_details_addresses_empty_add_hint: 'Create an address so people can open this app on your site.',
        app_details_add_route: 'Create address',
        app_details_manage_routes: 'All addresses',
        app_details_home_badge: 'Site homepage',
        app_details_danger_zone: 'Careful actions',
        app_data_storage: 'Space used',
        app_data_storage_hint: '{files} uploaded files · app itself {package}',
        app_data_storage_hint_files: '{files} uploaded files',
        app_data_storage_hint_package: 'App size: {package}',
        app_data_storage_empty: 'No files have been uploaded for this app yet',
        app_data_stat_files: 'Uploaded files',
        app_data_stat_users: 'Users',
        app_data_stat_routes: 'Addresses',
        app_data_stat_package: 'App size',
        app_data_stat_migrations: 'Database updates',
        app_data_stat_patches: 'Extra fixes',
        app_run: 'Open app',
        app_secret_view: 'View app',
        app_secret_view_hint: 'Open from here',
        app_back: 'Back',
        app_not_found_title: 'App not found',
        app_not_found_desc: 'This app is not installed or has already been removed.',
        app_settings: 'Settings',
        app_templates: 'Look',
        app_users_title: 'Users',
        app_users_intro: 'People who can sign in to this app.',
        app_users_platform_notice: 'This app shares the same users as Manager. Anyone listed here can also sign in to Manager with the same details.',
        app_users_platform_notice_form: 'They can also sign in to Manager with the same details.',
        app_users_add: 'Add user',
        app_users_search_placeholder: 'Name, email, or ID',
        app_users_filter_status: 'Status',
        app_users_filter_group: 'User group',
        app_users_filter_role: 'Role',
        app_users_filter_level: 'Role',
        app_users_filter_all: 'All',
        app_users_col_id: 'ID',
        app_users_col_name: 'Name',
        app_users_col_username: 'Username',
        app_users_col_mobile: 'Mobile',
        app_users_col_email: 'Email',
        app_users_col_status: 'Status',
        app_users_col_group: 'User group',
        app_users_col_roles: 'Roles',
        app_users_col_level: 'Role',
        app_users_col_date: 'Joined',
        app_users_col_actions: 'Actions',
        app_users_col_key: 'Key',
        app_users_empty_value: 'Not set',
        app_users_empty: 'No users yet',
        app_users_empty_filtered: 'No users match this search or filter',
        app_users_table_caption: 'Users of this app',
        app_users_count: '{count} users',
        app_users_roles_title: 'Roles',
        app_users_roles_caption: 'Each role decides what a user is allowed to do.',
        app_users_permissions_title: 'Permissions',
        app_users_permissions_caption: 'Actions defined for this app.',
        app_users_edit: 'Edit',
        app_users_delete: 'Delete',
        app_users_edit_role: 'Edit access',
        app_users_status_active: 'Active',
        app_users_status_inactive: 'Inactive',
        app_users_status_suspend: 'Suspended',
        app_users_status_pending: 'Pending',
        app_users_form_add_title: 'Add user',
        app_users_form_edit_title: 'Edit user',
        app_users_form_fname: 'First name',
        app_users_form_lname: 'Last name',
        app_users_form_username: 'Username',
        app_users_form_email: 'Email',
        app_users_form_mobile: 'Mobile',
        app_users_form_password: 'Password',
        app_users_form_password_hint: 'Leave empty to keep the current password.',
        app_users_form_status: 'Status',
        app_users_form_group: 'User group',
        app_users_form_group_hint: 'Can be left empty',
        app_users_form_group_none: 'No user group',
        app_users_form_roles: 'Roles',
        app_users_form_level: 'Role in this app',
        app_users_form_level_none: 'No role',
        app_users_level_admin: 'Admin',
        app_users_level_superadmin: 'Main admin',
        app_users_level_manager: 'App manager',
        app_users_level_user: 'User',
        app_users_level_editor: 'Editor',
        app_users_level_guest: 'Guest',
        app_users_form_save: 'Save',
        app_users_saved: 'User saved',
        app_users_save_failed: 'Could not save the user',
        app_users_deleted: 'User deleted',
        app_users_delete_failed: 'Could not delete the user',
        app_users_delete_title: 'Delete user',
        app_users_delete_lead: 'Remove this user from the app?',
        app_users_delete_hint: 'After deletion, they will no longer be able to sign in.',
        app_users_delete_confirm: 'Yes, delete',
        app_users_delete_self: 'You cannot delete your own account',
        app_users_page: 'Page',
        app_users_per_page: 'Per page',
        app_users_prev: 'Previous',
        app_users_next: 'Next',
        app_users_role_access_title: 'Role access',
        app_users_role_access_hint: 'Choose what this role is allowed to do.',
        app_users_role_access_saved: 'Role access saved',
        app_users_no_permissions: 'No permissions yet',
        app_users_no_roles_assigned: 'No role',
        app_users_access_button: 'Roles & access',
        app_users_access_title: 'Roles & access',
        app_users_access_hint: 'See the roles and permissions defined for this app.',
        app_users_access_empty: 'This app has no roles or permissions yet.',
        app_users_groups_title: 'Groups',
        app_users_perm_other: 'Other',
        app_templates_empty: 'No themes found',
        app_config_title: 'Settings',
        app_config_multi_route_title: 'Allow several addresses',
        app_config_multi_route_hint: 'When on, you can give this app more than one link.',
        app_badge_system: 'System',
        app_badge_hidden: 'Hidden from list',
        app_badge_no_dock: 'No quick shortcut',
        app_system_notice: 'This app is part of Pinoox, so it cannot be removed or started over here.',
        app_reset_title: 'Start over',
        app_reset_intro: 'The app’s data is cleared and set up again like day one. The app itself stays on your site.',
        app_reset_button: 'Start over',
        app_reset_lead: 'This app’s data will be cleared and rebuilt.',
        app_reset_hint: 'Saved data is removed and created again. This cannot be undone.',
        app_reset_purge_storage_title: 'Also delete uploaded files',
        app_reset_purge_storage_hint: 'Photos, documents, and other files uploaded for this app will be deleted too.',
        app_reset_confirm: 'Yes, start over',
        app_reset_progress: 'Starting over…',
        app_uninstall_title: 'Remove app',
        app_uninstall_intro: 'The app is removed from your site. You can also choose to delete its files and data.',
        app_uninstall_button: 'Remove app',
        app_stat_version: 'Version',
        app_stat_version_code: 'Version code',
        app_stat_developer: 'Made by',
        app_stat_package: 'App ID',
        app_stat_routing: 'Address type',
        app_stat_address_count: 'Address count',
        app_routing_single: 'One address',
        app_routing_multiple: 'Several addresses',
        template_activate_button: 'Use this look',
        template_delete_button: 'Delete look',
        template_active_badge: 'Current look',
        template_active_no_delete: 'The current look cannot be deleted.',
        template_delete_confirm: 'Do you want to delete this look?',
    },
};

export function resolveLocale(lang) {
    const code = String(lang ?? readActiveLang() ?? 'fa').toLowerCase();

    if (code.startsWith('fa')) {
        return 'fa';
    }

    return 'en';
}

function readActiveLang() {
    try {
        const store = useOptionsStore();

        if (store.lang) {
            return store.lang;
        }
    } catch {
        // Pinia may not be ready during early boot.
    }

    return getBoot().locale ?? document.documentElement.lang ?? 'fa';
}

export function translate(key, lang) {
    const locale = resolveLocale(lang);
    return MESSAGES[locale]?.[key] ?? MESSAGES.en[key] ?? key;
}

export function translateLevel(key, fallback = '') {
    const value = String(key || '').trim();

    if (value === '') {
        return translate('app_users_no_roles_assigned');
    }

    const i18nKey = `app_users_level_${value}`;
    const known = translate(i18nKey);

    if (known && known !== i18nKey) {
        return known;
    }

    const name = String(fallback || '').trim();

    if (name !== '' && name !== value) {
        return name;
    }

    return value.replace(/[_-]+/g, ' ');
}
